// shared inline style object (mobile-first)
const styles = {
  viewport: { minHeight: '100svh', width: '100%', display: 'grid', placeItems: 'center', background: 'linear-gradient(135deg,#eef2ff,#ffffff)', padding: 'clamp(12px,3vw,24px)' },
  centerWrap: { width: 'min(100%, 1024px)' },
  appCard: { width: '100%', background: '#fff', borderRadius: 20, boxShadow: '0 18px 60px rgba(2,6,23,.12)', overflow: 'hidden' },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 'clamp(8px,2vw,12px)', padding: 'clamp(12px,2.5vw,20px)', borderBottom: '1px solid #e2e8f0', flexWrap: 'wrap' },
  title: { fontSize: 'clamp(18px,4vw,24px)', fontWeight: 800, color: '#0f172a' },
  body: { padding: 'clamp(12px,2.5vw,20px)' },
  row: { display: 'flex', gap: 'clamp(10px,2vw,16px)', flexWrap: 'wrap' },
  card: { flex: '1 1 320px', background: '#fff', border: '1px solid #eef2f7', borderRadius: 16, boxShadow: '0 6px 24px rgba(15,23,42,.06)', padding: 'clamp(14px,2.5vw,20px)' },
  progressShell: { width: '100%', height: 12, borderRadius: 999, background: '#e2e8f0', overflow: 'hidden' },
  progressFill: (pct) => ({ height: '100%', width: pct + '%', background: '#6366f1', transition: 'width .3s' }),
  h2: { fontSize: 'clamp(16px,3.5vw,18px)', fontWeight: 700, margin: 0, marginBottom: 'clamp(6px,1.5vw,10px)', color: '#0f172a' },
  primary: { background: '#6366f1', color: '#fff', border: 0, padding: 'clamp(10px,2.5vw,12px) clamp(12px,3vw,14px)', borderRadius: 12, cursor: 'pointer', minHeight: 44, fontSize: 'clamp(14px,3.5vw,16px)' },
  ghost: { background: 'transparent', color: '#0f172a', border: '1px solid #cbd5e1', padding: 'clamp(10px,2.5vw,12px) clamp(12px,3vw,14px)', borderRadius: 12, cursor: 'pointer', minHeight: 44, fontSize: 'clamp(14px,3.5vw,16px)' },
  danger: { background: '#ef4444', color: '#fff', border: 0, padding: '8px 12px', borderRadius: 10, cursor: 'pointer', minHeight: 40 },
  input: { width: '100%', padding: 'clamp(10px,2.6vw,12px)', border: '1px solid #cbd5e1', borderRadius: 12, outline: 'none', background: '#fff', color: '#111827', minHeight: 44, fontSize: 'clamp(14px,3.5vw,16px)' },
  selectBtn: { width: '100%', padding: 'clamp(10px,2.6vw,12px)', border: '1px solid #d1d5db', borderRadius: 12, outline: 'none', background: '#f9fafb', textAlign: 'left', cursor: 'pointer', color: '#111827', minHeight: 44, fontSize: 'clamp(14px,3.5vw,16px)' },
  listItem: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, padding: '10px 0', borderBottom: '1px dashed #e2e8f0', flexWrap: 'wrap' },
  modalBackdrop: { position: 'fixed', inset: 0, background: 'rgba(2,6,23,.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 'clamp(10px,3vw,16px)', zIndex: 40 },
  modal: { position: 'relative', width: 'min(760px,100%)', background: '#fff', borderRadius: 16, boxShadow: '0 20px 60px rgba(2,6,23,.35)', padding: 'clamp(14px,2.5vw,20px)', zIndex: 60, maxHeight: '92svh', overflow: 'auto' },
  dropdown: { position: 'absolute', top: 'calc(100% + 6px)', left: 0, right: 0, background: '#fff', border: '1px solid #cbd5e1', borderRadius: 12, boxShadow: '0 10px 30px rgba(2,6,23,.15)', zIndex: 80, maxHeight: 220, overflowY: 'auto' },
  dropdownItem: { padding: '10px 12px', cursor: 'pointer', color: '#111827', background: '#fff', fontSize: 'clamp(14px,3.5vw,16px)' },
  dropdownItemActive: { padding: '10px 12px', cursor: 'pointer', color: '#111827', background: '#eef2ff', fontSize: 'clamp(14px,3.5vw,16px)' },
  hintWrap: { marginTop: 10, fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono','Courier New', monospace", display: 'flex', flexWrap: 'wrap', gap: 4 },
  hintEq: { background: '#dcfce7', color: '#14532d', padding: '2px 4px', borderRadius: 4 },
  hintSub: { background: '#fee2e2', color: '#7f1d1d', padding: '2px 4px', borderRadius: 4 },
  hintDel: { background: '#e0e7ff', color: '#3730a3', padding: '2px 4px', borderRadius: 4 },
  hintIns: { background: '#fde68a', color: '#7c2d12', padding: '2px 4px', borderRadius: 4 },
  hintLegend: { display: 'flex', gap: 8, alignItems: 'center', marginTop: 8, fontSize: 'clamp(11px,2.8vw,12px)', color: '#475569', flexWrap: 'wrap' },
  primarySm: {
    background: '#6366f1',
    color: '#fff',
    border: 0,
    padding: '6px 10px',
    borderRadius: 10,
    cursor: 'pointer',
    minHeight: 32,
    fontSize: 13,
    lineHeight: 1,
    whiteSpace: 'nowrap',
  },
  ghostSm: {
    background: 'transparent',
    color: '#0f172a',
    border: '1px solid #cbd5e1',
    padding: '6px 10px',
    borderRadius: 10,
    cursor: 'pointer',
    minHeight: 32,
    fontSize: 13,
    lineHeight: 1,
    whiteSpace: 'nowrap',
  },
  
};
export default styles;


